name:                gitissue
version:             0.1.0.0
github:              "d3zd3z/gitissue"
license:             BSD3
author:              "David Brown"
maintainer:          "davidb@davidb.org"
copyright:           "2018 David Brown"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/gitissue#readme>

dependencies:
- base >= 4.7 && < 5
- github >= 0.19 && < 0.20
- text >= 1.2 && < 1.3
- vector >= 0.12 && < 0.13

library:
  source-dirs: src

executables:
  gitissue:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gitissue

tests:
  gitissue-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gitissue
